spring:
    datasource:
        url: ${DB_URL:jdbc:postgresql://192.168.0.23:5432/logistics}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:1111}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO:update}
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
        serialization:
            write-dates-as-timestamps: false


    mail:
        host: ${SPRING_MAIL_HOST:smtp.gmail.com}
        port: ${SPRING_MAIL_PORT:587}
        username: ${SPRING_MAIL_USERNAME:tim92080888@gmail.com}
        password: ${SPRING_MAIL_PASSWORD:xxmsloufozroxicc}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: ${PORT:${SERVER_PORT:8080}}

app:
    cors:
        allowed-origin: ${APP_FRONTEND_ORIGIN:http://localhost:5173}
    jwt:
        secret: ${APP_JWT_SECRET:1234567890123456789012345678901234567890123456789012345678901234}
        access-expiration-minutes: ${APP_JWT_EXP_MIN:60}

    tmap:
        app-key: ${TMAP_APP_KEY:58gaUoZNnGcuRTIDz7hD5PxkVw8wd6nxyZYwhVc0}

    upload-dir: ${APP_UPLOAD_DIR:uploads}
    mail:
        from: ${APP_MAIL_FROM:${SPRING_MAIL_USERNAME:tim92080888@gmail.com}}
        from-name: ${MAIL_FROM_NAME:want}
